config/routes.rb
Weightable::Application.routes.draw do

  devise_for :users

  root :to => "users#index"

  get "/users/everyone" => "users#everyone"
  get "/users/weighin" => "users#weighin"

  resources :users, only: [:show, :index, :edit, :update] 
  resources :weighins, only: [:new, :create, :show]
  

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  
  belongs_to :weighins

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :weighins
  has_many :friends, through: :weighins

  mount_uploader :user_image, ImageUploader       

  def new
    @user = User.new
  end

end

app/models/weighin.rb
class Weighin < ActiveRecord::Base

  belongs_to :user
  has_many :friends

  mount_uploader :weigh_image, ImageUploader 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_action :authenticate_user!
before_filter :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
  [:first_name, :last_name, :start_weight, :goal_weight, :about, :user_image].each do |field|
    devise_parameter_sanitizer.for(:sign_up) << field
    devise_parameter_sanitizer.for(:account_update) << field
  end
end

def after_sign_in_path_for(resource)
  user_path(current_user.id)
end



end

app/controllers/registrations_controller.rb
class Devise::RegistrationsController < DeviseController

end

app/controllers/sessions_controller.rb
class Devise::SessionsController < DeviseController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :set_user, only: [:show, :edit, :update, :destroy]
  # before_action :correct_user, only: [:edit, :update]



  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def everyone
    @users = User.all
  end

  def weighin
  end

end

app/controllers/weighins_controller.rb
class WeighinsController < ApplicationController

def show
  @weighin = Weighin.new
end

# def show
#   @weighin = Weighin.find(params[:id])
# end

def new
  @weighin = Weighin.new
end

def create
  @weighin = current_user.weighins.build(weighin_params)
  if @weighin.save
    redirect_to user_path(current_user.id), :notice => "Your post saved"
  else
    redirect_to root_path, :notice => "Your post didn't save"
  end
end

# def edit
# end

# def destroy
# end
  
  private 

  def weighin_params
    params.require(:weighin).permit(:todays_weight, :weigh_image, :comments, :user_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weightable</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1>
        <%= link_to 'Home', root_url %>
      </h1>
    </li>
    <li class="toggle-topbar menu-icon">
      <a href="#">
        <span>Menu</span>
      </a>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <% if user_signed_in? %>

         <li>
          <%= link_to 'All Users', users_everyone_path %>
        </li>
        <li>
          <%= link_to 'My Account', user_path(current_user.id) %>
        </li>
        <li>
          <%= link_to 'Edit Profile', edit_user_registration_path %>
        </li>
        <li>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign up", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "Sign in", new_user_session_path %>
        </li>
      <% end %>
    </ul>
  </section>
</nav>










<%= yield %>

</body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8">
        
        <!-- Version 4.3.2 -->
        <link rel="stylesheet" href="http://cdn.jsdelivr.net/foundation/4.3.2/css/foundation.css">
        
        <!-- put in font awesome -->
        <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
        
        <!-- put in google fonts -->
        <link href='http://fonts.googleapis.com/css?family=Karla' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Shojumaru' rel='stylesheet' type='text/css'>
        
        <link href='style.css' rel='stylesheet' type='text/css'>
        <style type="text/css">

              /*This is used to see help see your 12 column grid*/
              /** {
              border: 1px solid red;
              -moz-box-sizing: border-box;
              -webkit-box-sizing: border-box;
              box-sizing: border-box;
              }*/
              /* You will put the rest of the styles here */
        </style>
    </head>
    <body>
      
      <!-- Title -->    
        <div class="row">
          <div class="large-12 columns">
            <h1> Weigtable </h1>
            <p> Join us in a healther life! Track your weight and encourage your friends to do the same!" <p>
          </div>
        </div>  


      <!-- Weightable Banner -->
        <div class="row">
        <div class="large-10 columns">
          <!-- Weightable - place in a paragraph to enforce the modular scale spacing -->
          <p><img src="images/banner.jpg" /></p>
        </div>
      </div>
    </body>
  </html>

app/views/users/_form.html.erb
<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8">
        
        <!-- Version 4.3.2 -->
        <link rel="stylesheet" href="http://cdn.jsdelivr.net/foundation/4.3.2/css/foundation.css">
        
        <!-- put in font awesome -->
       <!--  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"> -->
        
        <!-- put in google fonts -->
        <link href='http://fonts.googleapis.com/css?family=Michroma|Maven+Pro' rel='stylesheet' type='text/css'>
        
        <link href='style.css' rel='stylesheet' type='text/css'>
        <style type="text/css">

              /*This is used to see help see your 12 column grid*/
              /** {
              border: 1px solid red;
              -moz-box-sizing: border-box;
              -webkit-box-sizing: border-box;
              box-sizing: border-box;
              }*/
              /* You will put the rest of the styles here */
        </style>
    </head>
    <body>
          <%= form_for(@menu_item) do |f| %>
            <% if @menu_item.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

                <ul>
                <% @menu_item.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <p>
              <%= f.label "name:" %>
              <%= f.text_field :name %>
            </p>
              <%= f.label  "description:" %>
            <br>
              <p><%= f.text_area :description %></p>
               <p>
              <%= f.label "price:" %>
              <br>
              <%= f.text_field :price %>
            </p>
            <div class="actions">
              <%= f.submit %>
            </div>
          <% end %>
        </body>
      </html>

app/views/users/everyone.html.erb
<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8">
        
        <!-- Version 4.3.2 -->
        <link rel="stylesheet" href="http://cdn.jsdelivr.net/foundation/4.3.2/css/foundation.css">
        
        <!-- put in font awesome -->
       <!--  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"> -->
        
        <!-- put in google fonts -->
        <link href='http://fonts.googleapis.com/css?family=Michroma|Maven+Pro' rel='stylesheet' type='text/css'>
        
        <link href='style.css' rel='stylesheet' type='text/css'>
        <style type="text/css">

              /*This is used to see help see your 12 column grid*/
              /** {
              border: 1px solid red;
              -moz-box-sizing: border-box;
              -webkit-box-sizing: border-box;
              box-sizing: border-box;
              }*/
              /* You will put the rest of the styles here */
        </style>
    </head>
    <body>
    <div class="row">
      <div class="large-12 columns">
        <h2>Find a Friend</h2>
      </div>
    </div>
    <div class="row">
      <div class="large-1 columns"></div>
      <div class="large-11 columns">
        <% @users.each do |user| %>
        <h4 id = "link">
          <%= link_to user.first_name, user_path(user.id) %> 
          <%= link_to user.last_name, user_path(user.id) %>
        </h4>
        <p><%= user.about.truncate(35) %></p>
        <p><%= image_tag user.user_image.url(:thumb).to_s  %></p>
        <br>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8">
        
        <!-- Version 4.3.2 -->
        <link rel="stylesheet" href="http://cdn.jsdelivr.net/foundation/4.3.2/css/foundation.css">
        
        <!-- put in font awesome -->
       <!--  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"> -->
        
        <!-- put in google fonts -->
        <link href='http://fonts.googleapis.com/css?family=Michroma|Maven+Pro' rel='stylesheet' type='text/css'>
        
        <link href='style.css' rel='stylesheet' type='text/css'>
        <style type="text/css">

              /*This is used to see help see your 12 column grid*/
              /** {
              border: 1px solid red;
              -moz-box-sizing: border-box;
              -webkit-box-sizing: border-box;
              box-sizing: border-box;
              }*/
              /* You will put the rest of the styles here */
        </style>
    </head>
    <body>
      
      <!-- Title -->    
        <div class="row">
          <div class="large-12 columns">
            <h1> WEIGHTABLE </h1>
          </div>
        </div>  

        <div class="row">
          <div class="large-12 columns">
            <h5 class="intro"> Join us in a healther lifestyle today! Track your weightloss and encourage your friends to do the same.</h5>
          </div>
        </div>  




      <!-- Weightable Banner -->
        <div class="row">
          <div class="large-4 columns"></div>
          <!-- Weightable - place in a paragraph to enforce the modular scale spacing -->
          <div class="large-8 columns">
            <p><%= image_tag "man_opt.png" %></p>
          </div>
        </div>
      </body>
    </html>

app/views/users/show.html.erb
<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8">
        
        <!-- Version 4.3.2 -->
        <link rel="stylesheet" href="http://cdn.jsdelivr.net/foundation/4.3.2/css/foundation.css">
        
        <!-- put in font awesome -->
       <!--  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"> -->
        
        <!-- put in google fonts -->
        <link href='http://fonts.googleapis.com/css?family=Michroma|Maven+Pro' rel='stylesheet' type='text/css'>
        
        <link href='style.css' rel='stylesheet' type='text/css'>
        <style type="text/css">

              /*This is used to see help see your 12 column grid*/
              /** {
              border: 1px solid red;
              -moz-box-sizing: border-box;
              -webkit-box-sizing: border-box;
              box-sizing: border-box;
              }*/
              /* You will put the rest of the styles here */
        </style>
    </head>
    <body>
    <div class="row">
      <div class="large-9 columns">
        <h2><%= @user.first_name%> <%= @user.last_name %> </h2>
      </div>
    </div>
    <div class="row">
    
      <div class="large-5 columns">
        <h5><font color="#ff6933">ABOUT: </font color><%= @user.about %> </h5>
        
        <h5><font color="#ff6933">START WEIGHT: </font color><%= @user.start_weight %> pounds </h5>
        
        <h5><font color="#ff6933">GOAL WEIGHT: </font color><%= @user.goal_weight %> pounds </h5>
        
          <p><div id="img"><%= image_tag @user.user_image.url(:medium)  %></div></p>
          <br>
        <h6> <%= link_to 'Post New Weight', users_weighin_path %> </h6>
      </div>
      <div class="large-1 columns"></div>
      <div class="large-6 columns">
        <h5><font color="#ff6933">MY WEIGHT UPDATES: </font color></h5>
           <% @user.weighins.each do |weighin| %>
            <h5><%= weighin.created_at.strftime("%m/%d/%Y")%></h5>
            <p>&nbsp &nbsp <font color= "#5128A4"><em> <%= weighin.todays_weight %> pounds</em></font color></p>
            <p>&nbsp &nbsp <%= weighin.comments %></p>
            <p>&nbsp &nbsp <%= image_tag weighin.weigh_image.url(:thumb) %></p>
          
            <p> &nbsp &nbsp Post comment</p>
            <br>


             
            
          <%end%>
      </div>
    </div>
  </body>
</html>

app/views/users/weighin.html.erb
<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8">
        
        <!-- Version 4.3.2 -->
        <link rel="stylesheet" href="http://cdn.jsdelivr.net/foundation/4.3.2/css/foundation.css">
        
        <!-- put in font awesome -->
       <!--  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"> -->
        
        <!-- put in google fonts -->
        <link href='http://fonts.googleapis.com/css?family=Michroma|Maven+Pro' rel='stylesheet' type='text/css'>
        
        <link href='style.css' rel='stylesheet' type='text/css'>
        <style type="text/css">

              /*This is used to see help see your 12 column grid*/
              /** {
              border: 1px solid red;
              -moz-box-sizing: border-box;
              -webkit-box-sizing: border-box;
              box-sizing: border-box;
              }*/
              /* You will put the rest of the styles here */
        </style>
    </head>
    <body>
      <div class="row">
        <div class="large-9 columns">
          <h2>Post Today's Weight</h2>
        </div>
      </div>
      
      <div class="row">
       <div class="large-2 columns"></div>
       <div class="large-6 columns">
          <% @weighin = Weighin.new %>
          <%= render 'form' %>


          <%= link_to 'Back', user_path(current_user.id) %>
        </div>    
        <div class="large-4 columns"></div>  
      </div>  
    </body>
  </html>